name: Format Scripts

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Unity Auto Format
        uses: tyirvine/Unity-Actions-Autoformat@1.0.6
        with:
          path: ./Assets/Scripts/
